[general]
import = ["~/.config/alacritty/themes/kanagawa.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
# decorations = "Buttonless"
startup_mode = "Maximized"
opacity = 1

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux -f ~/.config/tmux/tmux.conf new-session -A -s main \\; send-keys 'neofetch' C-m"]

[font]
normal.family = "Hack Nerd Font Mono"
size = 16

[cursor]
unfocused_hollow = true
style = { blinking = "Never" }

